name: intrencity
description: "A new Flutter project."
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  smooth_corners:
    path: ./smooth_corners

  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.1
  another_dashed_container: ^1.0.0
  google_fonts: ^6.2.1
  lottie: ^3.1.2
  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  email_validator: ^3.0.0
  country_picker: ^2.0.26
  provider:
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.5.1
  image_picker: ^1.1.2
  speech_to_text: ^7.0.0
  carousel_slider: ^5.0.0
  firebase_storage: ^12.3.3
  intl: ^0.19.0
  shimmer: ^3.0.0
  currency_picker: ^2.0.21
  uuid: ^4.5.1
  fluttertoast: ^8.2.12
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  permission_handler: ^11.4.0
  riverpod_annotation: ^2.6.1
  file_picker: ^10.0.0
  open_filex:
  flutter_pdfview: ^1.4.0
  http: ^1.3.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  marquee: ^2.3.0
  flutter_otp_text_field: ^1.5.1+1
  # http: ^1.3.0
  # path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
